### ISSUE TITLE
Check size of files to be uploaded

### ISSUE THREAD

**Issue by christianmalek** [cmllr/redundancy#110]
Problem issued by https://github.com/Th3f

If a file is bigger than the space contingent the upload should'nt be possible and the user should be noticed.

I recommend a two-step implementation:
1. Check, if files to be uploaded > contingent
2. Check if files to be uploaded > free space (of contingent)

**Comment by cmllr** [comment]
When the new file exceeds the contingent of the user, an error is displayed.

Only when the server sends an false result (e. g. when Timeout or Session killed), there may be a wrong result.

_I need the error_log for finding this problem_
