### ISSUE TITLE
Some initial row values for admin user after installation are wrong

### ISSUE THREAD

**Issue by markhaehnel** [cmllr/redundancy#126]
Wrong entries:
- mailAdress (isn't even required on install)
- registrationDate

**Comment by cmllr** [comment]
Define wrong

**Comment by markhaehnel** [comment]
registrationDate = 2014-09-21 15:33:45 (should be 2015-02-22 ??:??:??)
mailAdress = test@bla.de (should be empty?)

**Comment by cmllr** [comment]
General question: Do we need support of sending mails?

**Comment by markhaehnel** [comment]
For password recovery?

**Comment by cmllr** [comment]
On a local server with probably not configured mailserver?

**Comment by markhaehnel** [comment]
PHP has the magic capability to send mails without any configuration.

**Comment by christianmalek** [comment]
:+1: for pw recovery
