### ISSUE TITLE
Bug/improvement: Handling of limited permissions

### ISSUE THREAD

**Issue by lebochequirit** [cmllr/redundancy#147]
When defining a group eg. public with limited permissions
- no sharing
- no deleting

users in the group still can see and click the related menu entries.
Suggested improvement: remove or at least grey out non-accessible entries
Suggested improvement: do not let restricted users see what permissions they don't have :-)

When clicking on "share" as a user not allowed to share, an error message is displayed, but the share link is created anyway. 
Suggested bugfix: abort before creating a share link

When a share link is created, a file cannot be deleted (which is most likely an mySQL issue, deleting the entry in the FileSystem table also gives an error message complaining there's a relation to the SharedFileSystem table). 
Suggested bugfix: when deleting a file, check for shares and either silently remove them or ask for OK/abort.

Great work so far, I'm really happy with rdcy.

L.B.Q.R.

**Comment by cmllr** [comment]
This issue is now partially fixed.

The only exception is the Delete Button in the context menu. Currently I cannot hide it b/c of the used jQuery Plugin. Maybe @Phisherman can help?

**Comment by cmllr** [comment]
@lebochequirit I could not reproduce your second issue. Could you tell me more? 

(I would be thankful if you could answer in #148 :) )

**Comment by cmllr** [comment]
The permission "AllowDeleteFromUserInterface" controls the vibibility of the delete button in the context menu. 

![Contextmenu](http://img.0fury.de/5a6851910207230f1a010d17a9ab5d71.png)

Please note: Only the permissions of the root group are currently automatically updated. To update other groups, please use the admin panel and save the groups (I am working on a better solution for 2.0).
