### ISSUE TITLE
Bug: Changing User in admin backend does not affect DB entry

### ISSUE THREAD

**Issue by lebochequirit** [cmllr/redundancy#149]
Version 1.9.2
Somewhat critical

As administrator, I pick a user, change the group from 'users' to 'public' (restricted to upload, delete, no sharing). Message says "user successfully updated" or so.

Logging in with that user, I still have 'user' rights.
Relogging in as Admin, picking user, the user is in group 'users' again.

Changing the role manually in mySQL, it is properly displayed in the admin backend when picking the user.

L.B.Q.R.

**Comment by cmllr** [comment]
Please update your version using a forced update:

`http://yourip/path/?update&go`
