### ISSUE TITLE
No Feedback when upload exeeds quota, echoing "No space left" when uploading duplicate files

### ISSUE THREAD

**Issue by miicchhii** [cmllr/redundancy#17]
When uploading a file which is too big (lets assume quota is 5MB, 4MB are used already and uploaded file has 1.5MB) it stops uploading, but doesn't show a message.

When uploading the same file twice into the same directory, a pop-up appears saying "No space left", even when the file is 40kB and free space >1MB

**Comment by cmllr** [comment]
A better feedback usage is already implemented at the current development version. In the next version you will get a feedback message if your download failed or not. If the file already exists, you will get a different message.
