### ISSUE TITLE
Desktop sync client 

### ISSUE THREAD

**Issue by toXel** [cmllr/redundancy#18]
A desktop sync client similar to Dropbox.

**Comment by cmllr** [comment]
An API to connect Redundancy to clients is currently being developed. Maybe on the version after 1.9.10 an alpha version will be included (not 100 % sure!)

**Comment by cmllr** [comment]
Version 1.9.10 didn't worked, sry. But yesterday I've started to implement an API interface and a test client. I think a first version and a rudimentary test client will be included with the next commit(s).

**Comment by christianmalek** [comment]
Here's the rep for the windows client: https://github.com/squarerootfury/redundancy-windows-client
It's still in early development phase!
