### ISSUE TITLE
Freigabefunktion unklar

### ISSUE THREAD

**Issue by FlorianSch** [cmllr/redundancy#19]
Hallo,

der Eintrag betrifft die neuste Version von redundancy mit dem bootstrap desgin.

Wenn ich bei einer Datei auf den Freigeben klicke, ändert sich der Link in der Adresszeile. Sollte etwa dieser Link der Freigabe Link für eine Datei sein bzw. die gesamte Freigabefunktion sein?

Des Weiteren, verwende bitte ein anderes Symbol für "Datei/ Verzeichnis freigeben" , da dieses Symbol mit dem Symbol für Löschen indentisch ist.

**Comment by cmllr** [comment]
An der Dateiansicht wird explizit genau an dieser Stelle gearbeitet, da ich selbst noch nicht damit zufrieden bin. Auch die Icons werden sich vorraussichtlich noch ändern.

Ist aber wie erwähnt schon in Arbeit.

Danke für dein Feedback!

**Comment by christianmalek** [comment]
Hi FlorianSch, danke für deine angebrachte Kritik. Aktuell sind wir noch am Umstellen und Ausprobieren.  Schau am besten morgen nochmal rein. Dann sollte es verständlicher sein. :)

Den Link, den du siehst, ist nicht für das Teilen. Dazu musst du im Moment erst nochmal auf die Datei klicken und in den Detailinfos unten siehst du dann den Share link.

**Comment by FlorianSch** [comment]
Die Freigabefunktion funktioniert, aber man springt, nachdem man auf freigeben bei der entsprechenden Datei geklickt hat wieder zurück zum aktuellen Verzeichnis. Vielleict gäbe es die Möglichkeit hier, dass man, nachdem man auf Freigeben geklickt hat in der aktuellen Ansicht verbleibt und den Link markieren kann und dann über zurück oder den Verzeichnisname wieder im aktuellen Verzeichnis landet.

**Comment by christianmalek** [comment]
Sollte in 1.9.10 möglich sein.

**Comment by cmllr** [comment]
Wurde integriert.
