### ISSUE TITLE
Downloadfunktion bzw. Uploadfunktion fehlerhaft

### ISSUE THREAD

**Issue by FlorianSch** [cmllr/redundancy#20]
Hallo,

ich hab eine .vsd-Datei hochgeladen (Visio-Zeichnung) und erhalten dann folgenden Dateinamen, wie im Bild im Anhang mit Rot markiert. Dies ist mir auch schon mit einer .jar-Datei bzw. dtc.-Datei (CADE-Zeichnung) passiert. Und zwar wird der Dateiname von einfachen Anführungszeichen umrahmt und kann damit von manchen Programmen nicht mehr erkannt werden bzw. geöffnet werden. Dies ist aber auch bei Word-Dateien der Fall, wobei hier die Datei trotzdem geöffnet werden kann.

Noch eine schönen Abend.

![neues bild](https://f.cloud.github.com/assets/5459688/1144126/b59f03d6-1d74-11e3-9912-9d9571f6c1a2.jpg)

**Comment by cmllr** [comment]
Bitte teste die Funktion noch einmal.

**Comment by FlorianSch** [comment]
Hallo,

Fehler ist behoben und es funktioniert wieder einwandfrei.

**Comment by cmllr** [comment]
Sehr gut :).
