### ISSUE TITLE
Theme issues

### ISSUE THREAD

**Issue by cmllr** [cmllr/redundancy#22]
Designtechnisch besser angepasste Möglichkeit für ein Kuchendiagramm.

Bessere Ausnutzung des bisher nicht verwendeten Raums; Eventuelle Gestaltung nach http://www.forum-raspberrypi.de/attachment.php?thumbnail=1180

**Comment by christianmalek** [comment]
Ist 'ne gute Idee der Dateiauflistung wegen. In allen anderen Fälle halte ich es für unübersichtlicher. Und warum den Platz nicht verwenden, wenn man ihn hat?

**Comment by christianmalek** [comment]
Die Layoutveränderung wird nicht umgesetzt.

**Comment by cmllr** [comment]
Die Diagrammansicht wird erst mit der übernächsten Version überarbeitet.
