### ISSUE TITLE
Theme issue under last changed files

### ISSUE THREAD

**Issue by kvnsfr** [cmllr/redundancy#25]
Theme Bug
- Wird durch Aufrufen des Modules "Änderungen" hervorgerufen, falls der Benutzer noch keine Datei hochgeladen hat.

Screenshot:
![issue](https://f.cloud.github.com/assets/5247137/1175386/ff09535a-2157-11e3-8b43-e053d0ad2d1a.png)

**Comment by cmllr** [comment]
Bug behoben in 1.9.10-beta0.

Danke fürs Feedback!
