### ISSUE TITLE
File upload does not work if file bigger than 10 MB

### ISSUE THREAD

**Issue by FlorianSch** [cmllr/redundancy#30]
Hi,
i had already installed redudancy on my pi, but if i upload a file that is bigger than 10 MB the upload does not work an no error message like "upload fehlgeschlagen" appears with reason why this could happen.

**Comment by cmllr** [comment]
This feature is already implemented in the current development version and will be published with the next commit (1.9.11-git-beta1-r3) which will be committed in the next few days.

The maximum upload size depents on the maximum file size configured in your php.ini.
