### ISSUE TITLE
Dateien mit Leerzeichen und weitere Vorschläge

### ISSUE THREAD

**Issue by gfcwfzkm** [cmllr/redundancy#5]
-Dateien mit leerzeichen z.B. 'Dokument 12.doc' werden bei einem Download nur noch als 'Dokument.doc zurückgegeben.
-Videoupload ist gescheitert, die Datei (.wmv) war 42.7MB gross. 
-Mit der Funktion 'Link freigeben' sollte eine Art Textbox erscheinen, um den Link zu kopieren. Sonst öffnet sich nur eine neue Tab und der Download der Datei beginnt.

-Ebenso wäre ein Ladebalken beim Upload hilfreich.
-Eine Upload-Begrenzung.
-Eine Verlinkung unter 'info' auf diese Seite, für schnelleren und leichteren Fehlerreport.

**Comment by cmllr** [comment]
- Bug Nummer 1 kann ich nicht replizieren.
- Bug Nummer 2 hängt von der php.ini ab, kann ich daher nicht beeinflussen.
- Beim Teilen ist das so eine Sache, ich werde überlegen, wie ich das lösen kann.
- Uploadladebalken werde ich versuchen zu integrieren, jedoch muss ich da gucken inwieweit PHP - Erweiterungen notwendig werden.
- Was meinst du mit Upload - Begrenzung?
- Link ist drin.

**Comment by gfcwfzkm** [comment]
Bug 1: https://redundancy.pfweb.eu/Demo/index.php?share=sNPKBWjEAQJ3i8ZhCx2RHMuvgObwS56YqTz9InLtXydp0kmafl  Foto zum Fehler.

Mir fällt auf, das wenn man eine fotodatei anklickt, das diese dann Gross angezeigt wird. Wäre auch cool, wenn etwas ähnliches mit Video und Audiodateien so ist. (mp4, mp3 usw...)

**Comment by cmllr** [comment]
Ich werde mal gucken, ob sich da irgendetwas mit html5 oder so machen lässt

**Comment by cmllr** [comment]
Die Fehlerhafte Benennung der Downloads ist mit Version 1.9.10 behoben.
