### ISSUE TITLE
PW Änderungsfunktion in eigene Seite machen

### ISSUE THREAD

**Issue by christianmalek** [cmllr/redundancy#51]

**Comment by cmllr** [comment]
Meinst du die Änderung im Adminpanel?

**Comment by christianmalek** [comment]
Ja. Dort sind zu viele Funktionalitäten auf einem Haufen.

**Comment by cmllr** [comment]
Es ist halt ein Admin-Panel ;)

**Comment by christianmalek** [comment]
Kein Grund für Unübersichtlichkeit.

**Comment by christianmalek** [comment]
In Panels organisiert.
