### ISSUE TITLE
Französische Übersetzung anpassen

### ISSUE THREAD

**Issue by christianmalek** [cmllr/redundancy#52]
Folgende Variablen müssen übersetzt werden:

MyAccount = "Account";
AccountOf = "Konto von";

**Comment by christianmalek** [comment]
In der französcischen Übersetzung natürlich ;)

**Comment by cmllr** [comment]
Wird erst dann gemacht, wenn die deutsche Übersetzung vollständig ist.

**Comment by cmllr** [comment]
Btw, steht in #3
