### ISSUE TITLE
Can't install redundancy via install.php

### ISSUE THREAD

**Issue by FlorianSch** [cmllr/redundancy#65]
I can't install redundancy via install.php. I see only an empty site, if i go to install.php. Is there any workaround for the installation of the new redundancy version?

**Comment by cmllr** [comment]
Did you used the correct branch?

Does the PHP-Log prints something interesting?

Workaround:

Import Dump.sql

Open Includes/Kernel/Kernel.Config.class.php and enter your database credentials

Make sure that /Storage/ /Temp/ and /Snapshots/ are writable

Note: The priority is to fix the bug, not to offer workarounds. When the site does not display anything, it may be related to something in your Webserver/PHP -configuration

**Comment by FlorianSch** [comment]
The PHP Log says following: [Sun Oct 19 17:57:53 2014] [error] [client 192.168.100.86] PHP Parse error:  syntax error, unexpected ')', expecting '(' in /$' in /var/www/redun/Includes/Kernel/Kernel.Installer.class.php on line 114, referer: http://192.168.100.198/

 I use the lenticularis branch
/Storage/ /Temp/ and /Snapshots/ are writable

I hav ealso import the Dump.sql. and also wrote my database credentials into Kernel.Config.class.php

**Comment by cmllr** [comment]
PHP-Version? 

I recommend PHP 5.5.x.

**Comment by FlorianSch** [comment]
Okay, i have an older Version (5.4.4) on the github page for this branch there stand PHP 5.3 recommended

**Comment by cmllr** [comment]
Oh sh*t. Sorry, that was my fault. The readme is mostly taken from the old
version. I will correct that

2014-10-19 18:36 GMT+02:00 FlorianSch notifications@github.com:

**Comment by FlorianSch** [comment]
After updating PHP the installation has worked. FYI: the sourcelist for raspbian had to be changed from wheezy to jessie, because wheezy only supports PHP 5.4.

**Comment by cmllr** [comment]
Thanks for your feedback. This problem is a little bit strange. The error is a syntax error, because of that I cannot do any downward compalibity. So we may have to live with this problem. I hope that someday the debian sources will be updated to a newer version.
