### ISSUE TITLE
Font-Issues

### ISSUE THREAD

**Issue by cmllr** [cmllr/redundancy#66]
"Nur son Tipp bezüglich Design: Ich würde eine Schriftart nutzen, die ein wenig dicker ist. Vieles kann man nur schwer lesen"

Ich gehe davon aus, er meint primär die "light"-CSS-Klassen.

Von: https://twitter.com/ThiefasDE/status/524639426644041729

**Comment by christianmalek** [comment]
Das liegt am CSS. Das funktioniert komischerweise im Firefox nicht. Da wird der Text grau angezeigt. Wird bald gefixt.

**Comment by cmllr** [comment]
Kannst du mal schauen, wie du das fixen kannst? In FF ist das wohl recht extrem..

**Comment by elomatreb** [comment]
Guten Tag.

Ich weiß zwar nicht wie genau der hier behandelte Effekt aussieht (Ein Screenshot wäre hilfreich), jedoch kann ich eine Vermutung aufstellen.

Ich vermute, dass dieser Effekt durch einen zu dünn gewählten Schriftschnitt verursacht wird. Dieser Effekt tritt auf, da die eigentlich Schrift bei geringen Schriftgrößen nicht mehr gerendert wird und die Artefakte der Greyscale-Kantenglättung sichtbar werden (Auf anderen Systemen könnten auch rote oder blaue Artefakte auftreten, wenn diese Subpixel-Kantenglättung verwenden). Dieses könnte unter Windows bei Firefox auftreten (Da dieser einen eigenen Schriftrenderer verwendet), aber auch mit diversen WebKit-basierenden Browsern (besonders unter Linux oder OS X, welche sich in dieser Hinsicht generell etwas eigenartig verhalten) auftreten.

Am einfachsten währe dieses Problem wahrscheinlich zu lösen indem man bei Texten die keine besondere Schriftgröße haben, sich auf den Standartschnitt (`font-weight: 400`) verlässt. Ohnehin werden die sichtbaren Unterschiede, die ein verringern der Schriftstärke bei geringen Schriftgrößen hat, verschwindend gering.

PS: Leider konnte ich weder die erwähnten CSS-Klassen finden, noch konnte ich den Effekt replizieren.

**Comment by christianmalek** [comment]
Danke für die Info. Das wird es 100% sein.

**Comment by cmllr** [comment]
:+1:

**Comment by christianmalek** [comment]
Fixed in 8e163277d7c3dd9d6b9db5a1202c14e33d68f8da
