### ISSUE TITLE
'Komprimieren' durch 'Herunterladen' ersetzten

### ISSUE THREAD

**Issue by gfcwfzkm** [cmllr/redundancy#7]
Hi,

ich würde (Bei Ordner) anstatt 'Komprimieren' eher 'Herunterladen' hinsetzten (Mit üblichen Download-Icon). Weil ich habe beim probieren gedacht, das so meine Dateien AUF dem Server komprimiert werden (Mehr Speicherplatz ^-^).

mfg

gfc - Weiter so ;)

**Comment by cmllr** [comment]
Ist mit 1.9.9 integriert.

Schon Feedback möglich?
