### ISSUE TITLE
Implement AngularJS file viewer

### ISSUE THREAD

**Issue by christianmalek** [cmllr/redundancy#75]

**Comment by cmllr** [comment]
Or we use a kind of "mini Angular-Client" for the Files view...

**Comment by christianmalek** [comment]
I'll look into this.

**Comment by cmllr** [comment]
:+1:

**Comment by christianmalek** [comment]
For context menu: https://github.com/ianwalter/ng-context-menu

**Comment by christianmalek** [comment]
For text view: http://angular-ui.github.io/ui-ace/

**Comment by cmllr** [comment]
Cancelled for now.
