### ISSUE TITLE
High TTFB

### ISSUE THREAD

**Issue by markhaehnel** [cmllr/redundancy#82]
Redundancy is experiencieng a high TTFB.
It takes up to 10 seconds on my https testing environment.

Sometimes it's even worse:
![image](https://cloud.githubusercontent.com/assets/1516205/5432241/90fb7bfa-8438-11e4-98a0-c3059ecf662b.png)

**Comment by cmllr** [comment]
Server specs? Network connection? Query failures in error log?

**Comment by markhaehnel** [comment]
Hosted system at Uberspace.
Specs are:
6 Core Xeon, 12GB RAM, 100MBit connection.

But that's not the point. WordPress and OwnCloud are running fine and TTFB is under 2 seconds.
No errors in the logs.

**Comment by cmllr** [comment]
Redundancy and uberspace having a problem. See #53 

Maybe it would be interesting to look into errorlogs if there is something suspicious.

**Comment by markhaehnel** [comment]
Found something in the errorlog.

```
[Mon Dec 15 13:57:23 2014] [warn] mod_fcgid: stderr: PHP Warning: 
Invalid argument supplied for foreach() in
/var/www/virtual/mhaehnel/html/redundancy/Includes/Kernel/Kernel.System.class.php on line 109
```

Don't know if it is relevant for this issue.

**Comment by cmllr** [comment]
Nope, but will fix this

**Comment by christianmalek** [comment]
I had the same issues on uberspace. If you want to execute a script it needs to warm up. Maybe this is the root of all evil.

Look here: https://wiki.uberspace.de/development:php

**Comment by markhaehnel** [comment]
This can't cause the issues. The FastCGI instance spawning could only cause a longer TTFB on the first page visit.

**Comment by cmllr** [comment]
When Redundancy is running (kind of) stable, I will start to check and improve performance for one of the release candidate versions. But at the moment, this problem has no priority

**Comment by cmllr** [comment]
It could be that doctrine is the cause of this problem

**Comment by cmllr** [comment]
![ttfb](https://cloud.githubusercontent.com/assets/2878201/5569869/46afc3b2-8f78-11e4-83e2-ecbff2c1612b.png)

cUrl seems to be the reason.

**Comment by cmllr** [comment]
https://stackoverflow.com/questions/2445276/how-to-post-data-in-php-using-file-get-contents
