### ISSUE TITLE
Implement SQLite database connector

### ISSUE THREAD

**Issue by markhaehnel** [cmllr/redundancy#83]
Please. :stuck_out_tongue:

**Comment by christianmalek** [comment]
Isn't the libRedundancy made for that?

**Comment by markhaehnel** [comment]
libRedundancy is the interface for other _(desktop)_ applications to communicate with Redundancy.
It should be easy to implement SQLite as a alternative DBMS because of the identical queries.

**Comment by christianmalek** [comment]
You should mention that you want to replace the current DBMS. I thought you
need it for the desktop client.

Mark Hähnel notifications@github.com schrieb am Di., 16. Dez. 2014 16:15:

**Comment by markhaehnel** [comment]
I don't want to replace it, just add an additional one. It's lightweight, so it fits perfectly.

**Comment by cmllr** [comment]
Redundancy will support SQLite (abstracted with an DB-Layer). I will have to apply changes to several queries and the dump to get SQLite supported.

It will work at someday in the future, but not at the moment and not for the beta version.
